# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(816, 259)
        Dialog.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        Dialog.setStyleSheet("border-radius: 15px;\n"
"background-color: #0a182f;\n"
"color: white;")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalFrame = QtWidgets.QFrame(Dialog)
        self.horizontalFrame.setStyleSheet("background-color: #172a45;")
        self.horizontalFrame.setObjectName("horizontalFrame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalFrame)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.checkBox = QtWidgets.QCheckBox(self.horizontalFrame)
        self.checkBox.setStyleSheet("font: 12pt \"roboto\";")
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_5.addWidget(self.checkBox)
        self.verticalLayout_2.addWidget(self.horizontalFrame)
        self.tile_size_edit_frame = QtWidgets.QFrame(Dialog)
        self.tile_size_edit_frame.setStyleSheet("background-color: #172a45;")
        self.tile_size_edit_frame.setObjectName("tile_size_edit_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tile_size_edit_frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.tile_size_edit_frame)
        self.label.setStyleSheet("font: 12pt \"roboto\";")
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.tile_size_lcd_slider = QtWidgets.QSlider(self.tile_size_edit_frame)
        self.tile_size_lcd_slider.setMinimum(5)
        self.tile_size_lcd_slider.setMaximum(45)
        self.tile_size_lcd_slider.setOrientation(QtCore.Qt.Horizontal)
        self.tile_size_lcd_slider.setObjectName("tile_size_lcd_slider")
        self.horizontalLayout_2.addWidget(self.tile_size_lcd_slider)
        self.tile_size_lcd = QtWidgets.QLCDNumber(self.tile_size_edit_frame)
        self.tile_size_lcd.setObjectName("tile_size_lcd")
        self.horizontalLayout_2.addWidget(self.tile_size_lcd)
        self.verticalLayout_2.addWidget(self.tile_size_edit_frame)
        self.col_edit_frame = QtWidgets.QFrame(Dialog)
        self.col_edit_frame.setStyleSheet("background-color: #172a45;")
        self.col_edit_frame.setObjectName("col_edit_frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.col_edit_frame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.col_edit_frame)
        self.label_3.setStyleSheet("font: 12pt \"roboto\";")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.cols_lineEdit = QtWidgets.QLineEdit(self.col_edit_frame)
        self.cols_lineEdit.setStyleSheet("QLineEdit\n"
"{\n"
"    background-color: rgb(20, 50, 108);\n"
"    padding: 5px;\n"
"    border-style: solid;\n"
"    border-radius: 10px;\n"
"}")
        self.cols_lineEdit.setObjectName("cols_lineEdit")
        self.horizontalLayout_3.addWidget(self.cols_lineEdit)
        self.verticalLayout_2.addWidget(self.col_edit_frame)
        self.row_edit_frame = QtWidgets.QFrame(Dialog)
        self.row_edit_frame.setStyleSheet("background-color: #172a45;")
        self.row_edit_frame.setObjectName("row_edit_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.row_edit_frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.row_edit_frame)
        self.label_2.setStyleSheet("font: 12pt \"roboto\";")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.rows_lineEdit = QtWidgets.QLineEdit(self.row_edit_frame)
        self.rows_lineEdit.setStyleSheet("QLineEdit\n"
"{\n"
"    background-color: rgb(20, 50, 108);\n"
"    padding: 5px;\n"
"    border-style: solid;\n"
"    border-radius: 10px;\n"
"}")
        self.rows_lineEdit.setObjectName("rows_lineEdit")
        self.horizontalLayout.addWidget(self.rows_lineEdit)
        self.verticalLayout_2.addWidget(self.row_edit_frame)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setStyleSheet("QPushButton\n"
"{\n"
"       font-size: 10pt;\n"
"    background-color:  rgb(114, 57, 220);\n"
"    padding: 5px;\n"
"    border-radius: 10px;\n"
"    outline: none;\n"
"}")
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.rejected.connect(Dialog.reject)
        self.tile_size_lcd_slider.valueChanged['int'].connect(self.tile_size_lcd.display)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Настройки игры"))
        self.checkBox.setText(_translate("Dialog", "Показывать тень от фигурки"))
        self.label.setText(_translate("Dialog", "Размер ячейки"))
        self.label_3.setText(_translate("Dialog", "Количество столбцов"))
        self.label_2.setText(_translate("Dialog", "Количество строк"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
